### ISSUE TITLE
Commands out of sync; you can't run this command now

### ISSUE THREAD

**Issue by jkeys089** [mariano/node-db-mysql#100]
While attempting to execute a stored procedure I'm occasionally getting the "Commands out of sync; you can't run this command now" error.

It is my understanding that the problem is caused by me not cleaning up the additional result set being returned by the stored proc before attempting to call the procedure again.

I've seen solutions online (http://forums.mysql.com/read.php?52,140863,179132#msg-179132):

``` php
while (mysqli_more_results($dbc)) { 
    if (mysqli_next_result($dbc)) { 
        $result = mysqli_use_result($dbc); 
        mysql_free_result($result); 
    }
}
```

But I'm unsure how to work around this issue in db-mysql.

Any advice would be greatly appreciated.

**Comment by mariano** [comment]
Closed in b86bc68
