### ISSUE TITLE
Failed at the db-mysql@0.7.6 install script.

### ISSUE THREAD

**Issue by sensorario** [mariano/node-db-mysql#104]
npm ERR! db-mysql@0.7.6 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 127
npm ERR!
npm ERR! Failed at the db-mysql@0.7.6 install script.
npm ERR! This is most likely a problem with the db-mysql package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls db-mysql
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.5.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "db-mysql"
npm ERR! cwd /Users/simonegentili/Desktop/stack-question
npm ERR! node -v v0.10.6
npm ERR! npm -v 1.2.18
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/simonegentili/Desktop/stack-question/npm-debug.log
npm ERR! not ok code 0

**Comment by Lesanjo** [comment]
Got the same errors, have you had some luck installing it?

**Comment by rmmaheshwari** [comment]
getting same error.

102 info build /usr/local/lib/node_modules/db-mysql
103 verbose linkStuff [ true,
103 verbose linkStuff   '/usr/local/lib/node_modules',
103 verbose linkStuff   true,
103 verbose linkStuff   '/usr/local/lib/node_modules' ]
104 info linkStuff db-mysql@0.7.6
105 verbose linkBins db-mysql@0.7.6
106 verbose linkMans db-mysql@0.7.6
107 verbose rebuildBundles db-mysql@0.7.6
108 info install db-mysql@0.7.6
109 verbose unsafe-perm in lifecycle false
110 info db-mysql@0.7.6 Failed to exec install script
111 info /usr/local/lib/node_modules/db-mysql unbuild
112 info preuninstall db-mysql@0.7.6
113 verbose unsafe-perm in lifecycle false
114 info uninstall db-mysql@0.7.6
115 verbose true,/usr/local/lib/node_modules,/usr/local/lib/node_modules unbuild db-mysql@0.7.6
116 info postuninstall db-mysql@0.7.6
117 error db-mysql@0.7.6 install: `node-waf configure build`
117 error Exit status 127
118 error Failed at the db-mysql@0.7.6 install script.
118 error This is most likely a problem with the db-mysql package,
118 error not with npm itself.
118 error Tell the author that this fails on your system:
118 error     node-waf configure build
118 error You can get their info via:
118 error     npm owner ls db-mysql
118 error There is likely additional logging output above.
119 error System Linux 3.11.0-14-generic
120 error command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "db-mysql"
121 error cwd /home/radham
122 error node -v v0.11.10-pre
123 error npm -v 1.3.17
124 error code ELIFECYCLE
125 verbose exit [ 1, true ]

**Comment by DJchopstix13** [comment]
npm http GET https://registry.npmjs.org/db-mysql
npm http 304 https://registry.npmjs.org/db-mysql

> db-mysql@0.7.6 install /Users/jpiatos13/Dropbox/school-files/LMU/cs/github/senior-project/indieD/node_modules/db-mysql
> node-waf configure build

sh: node-waf: command not found

> db-mysql@0.7.6 preuninstall /Users/jpiatos13/Dropbox/school-files/LMU/cs/github/senior-project/indieD/node_modules/db-mysql
> rm -rf build/*

npm ERR! db-mysql@0.7.6 install: `node-waf configure build`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the db-mysql@0.7.6 install script.
npm ERR! This is most likely a problem with the db-mysql package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls db-mysql
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "db-mysql"
npm ERR! cwd /Users/jpiatos13/Dropbox/school-files/LMU/cs/github/senior-project/indieD
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/jpiatos13/Dropbox/school-files/LMU/cs/github/senior-project/indieD/npm-debug.log
npm ERR! not ok code 0

**Comment by Skoua** [comment]
It seems that node-waf is deprecated and has been replaced by node-gyp.

**Comment by kameshveera** [comment]
Hi all
i got same error

$ npm install db-mysql
/

> db-mysql@0.7.6 install e:\xampp\htdocs\test\knode\test\node_modules\db-mysql
> node-waf configure build

'node-waf' is not recognized as an internal or external command,
operable program or batch file.

> db-mysql@0.7.6 preuninstall e:\xampp\htdocs\test\knode\test\node_modules\db-my
> sql
> rm -rf build/*

npm ERR! db-mysql@0.7.6 install: `node-waf configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the db-mysql@0.7.6 install script.
npm ERR! This is most likely a problem with the db-mysql package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls db-mysql
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "c:\Program Files\nodejs\node.exe" "c:\Program Files\nodej
s\node_modules\npm\bin\npm-cli.js" "install" "db-mysql"
npm ERR! cwd e:\xampp\htdocs\test\knode\test
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     e:\xampp\htdocs\test\knode\test\npm-debug.log
npm ERR! not ok code 0

Please any one help me.

**Comment by flocsy** [comment]
Hi,

is node-db-mysql dead? This bug is more than half a year open and no response

**Comment by sensorario** [comment]
I think I'll close this issue.
