### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _mysql_init

### ISSUE THREAD

**Issue by agoes82** [mariano/node-db-mysql#17]
Hi I have problem with the dyld, I using XAMPP package for mysql and the using MacBook Pro, Model Identifier:   MacBookPro7,1, Processor Name:  Intel Core 2 Duo

The error it's 

dyld: lazy symbol binding failed: Symbol not found: _mysql_init
  Referenced from: /opt/local/lib/node/.npm/db-mysql/0.6.5/package/build/default/mysql_bindings.node
  Expected in: dynamic lookup

dyld: Symbol not found: _mysql_init
  Referenced from: /opt/local/lib/node/.npm/db-mysql/0.6.5/package/build/default/mysql_bindings.node
  Expected in: dynamic lookup

Do you have any idea what's going on. Cause i have tried this link but no luck http://bixsolutions.net/forum/printthread.php?tid=18

Regards
Setyagus Sucipto

**Comment by mariano** [comment]
I'd love to help out, unfortunately Apple makes it hard for us linux devs to provide support for you Mac devs, since it does not allow a virtual machine installation of its OS.

I do know that several other db-mysql users use macs and had no issues with it. For example, [people that installed mysql via homebrew](https://github.com/mariano/node-db-mysql/issues/2) or people [using MAMP](https://github.com/mariano/node-db-mysql/issues/1)

Can you get into db-mysql directory and run the following, and give me the output?

$ rm -fr build/ && node-waf configure build --verbose

**Comment by agoes82** [comment]
Hi Mariano thank you for your feedback.

I have tried install the mysql 5.5.13 from mysql.com but still no luck too. 

Setyagus-Suciptos-MacBook-Pro:db-mysql agoes82$ pwd
/opt/local/lib/node/.npm/db-mysql
Setyagus-Suciptos-MacBook-Pro:db-mysql agoes82$ rm -fr build/ && node-waf configure build --verbose
arg[0] directory does not contain a wscript file

**Comment by mariano** [comment]
If it says no wscript file, it's because you are standing in the wrong directory.

You should be in a directory where a file named wscript is. Can you list the contents where you are?

If not installing the module locally, this should be node_modules/db-mysql

**Comment by agoes82** [comment]
Sorry it was wrong folder, this is an output that you need
http://dl.dropbox.com/u/1125469/db-mysql.log.data

**Comment by mariano** [comment]
Try not to close the issue :)

**Comment by mariano** [comment]
Ok this is telling you something:

```
ld: warning: in /Applications/XAMPP/xamppfiles/lib/mysql/libmysqlclient_r.dylib, missing required architecture x86_64 in file
ld: warning: in /Applications/XAMPP/xamppfiles/lib/libz.dylib, missing required architecture x86_64 in file
```

It seems you have a problem with the architecture

**Comment by mariano** [comment]
Also what mysql version is that? Since I see an issue documented on mysql:

http://bugs.mysql.com/bug.php?id=41940

**Comment by agoes82** [comment]
Hi Mario now the problem solve, i change it into 64 bits version --> http://dl.dropbox.com/u/1125469/db-mysql.log.data.2 

But I have another problem. the system can't load library libmysqlclient.16.dylib --> http://dl.dropbox.com/u/1125469/node-js-db-mysql.log.error.1

I checking the mysql_config - http://dl.dropbox.com/u/1125469/mysql-config.log.1

and this one the list of files http://dl.dropbox.com/u/1125469/ls.list.lib.mysql.log

regards
Setyagus Sucipto

**Comment by mariano** [comment]
Could you please document on this ticket how you changed it to 64 bits, so other people can find this useful?

Also, your second file is empty for me (the mysql_config dump)

**Comment by agoes82** [comment]
Please check again, I reupload the fiel on the dropbox. Will write step by step after this comment.

**Comment by mariano** [comment]
Still empty. Can't you paste in some pastebin, like http://pastium.org ?

**Comment by agoes82** [comment]
The problem solve for the:
dyld: lazy symbol binding failed: Symbol not found: _mysql_init
Referenced from: /opt/local/lib/node/.npm/db-mysql/0.6.5/package/build/default/mysql_bindings.node
Expected in: dynamic lookup

The problem it's on the different architecture between 32bits and 64 bits, you can check your architecture in http://support.apple.com/kb/HT3696

Please download the mysql package from here http://dev.mysql.com/downloads/mysql/5.0.html#downloads choose the DMG Archive 

attention : If your mysql it's not package from XAMPP or MAMP you can just change the you /usr/local/mysql into the mysql 64 bits folder
1. Shutdown all your mysql service 
   $ sudo /usr/libexec/locate.updatedb (will take your time cause this will locate all your file)
2. Remove your default mysql_config cause we need set the new mysql_config
   $ cd /usr/sbin/
   $ sudo rm mysql_config
3. Go to your folder /usr/local for checking your mysql 
   $ cd /usr/local/
   $ ls -al | grep mysql
4. Link your mysql into the mysql 64 bit
   $ sudo rm mysql (if this link it will remove the link not physical file, if this physical file please make sure you already backup your datadir)
   $ sudo ln -s mysql-5.6.2-m5-osx10.6-x86_64 mysql
5. Link your new mysql_config into sbin directory
   $ sudo ln -s /usr/local/mysql/bin/mysql_config /usr/sbin/mysql_config (or you can change the folder mysql into your physical folder in mysql-5.6.2-m5-osx10.6-x86_64)
   $ sudo chmod +x /usr/local/mysql/bin/mysql_config
6. go to your node-js package in my place it's on /opt/local/lib/node/.npm/db-mysql/active/package
   $ cd /opt/local/lib/node/.npm/db-mysql/active/package
   $ rm -fr build/ && node-waf configure build --verbose
7. Done you already switch the mysql version, but please make sure you configure the datadir - http://niblets.wordpress.com/2007/03/23/changing-your-mysql-data-directory/

If you can't connect into mysql please check your socket configuration in my.cnf and change it.

**Comment by agoes82** [comment]
Hi Mario this is the config http://pastium.org/view/4a35aeb1bf856634d7185df9704af128

**Comment by agoes82** [comment]
Mario for this problem 

Error: dlopen(/opt/local/lib/node/.npm/db-mysql/0.6.5/package/build/default/mysql_bindings.node, 1): Library not loaded: libmysqlclient.16.dylib
  Referenced from: /opt/local/lib/node/.npm/db-mysql/0.6.5/package/build/default/mysql_bindings.node

I can fix it using this command line 
$ export DYLD_LIBRARY_PATH=/usr/local/mysql/lib/

But i have another problem again
Assertion failed: (handle->InternalFieldCount() > 0), function Wrap, file ../src/node_object_wrap.h, line 61.

Regards
Setyagus Sucipto

**Comment by agoes82** [comment]
Hi Mario it's working now. Thank you for your support.

regards
Setyagus Sucipto

**Comment by mariano** [comment]
@agoes82: Thanks for reporting the fixes, this will surely help other Mac users.

What was the fix for the last issue (InternalFieldCount)? Did you forget to do new Database?

**Comment by chenmingqiang** [comment]
cool, I also faced the same issue. That's a good guide for me.
