### ISSUE TITLE
Error when Installing on Mac with NPM

### ISSUE THREAD

**Issue by adamhalasz** [mariano/node-db-mysql#18]
Last time I had similar issues with my macbook but there I figured out, but now I'm switching to an iMac, I just reinstalled the OS on it, and I have errors again when I try to install db-mysql.

I have Node.js 0.4.8, Mac OS X 10.6.7, and MySQL 5.5.13

The mysql_config is at: /usr/local/mysql/bin/mysql_config , I know this because I tested it by going to Finder->Command+Shift+G -> /usr/local/mysql/bin and mysql_config is there

I'm trying to install it with:
`export MYSQL_CONFIG=/usr/local/mysql/bin/mysql_config
npm install db-mysql`

But I get:

```
> db-mysql@0.6.6 install /Users/adamfisher/node_modules/db-mysql
> node-waf configure build

Checking for program g++ or c++          : not found 
/Users/adamfisher/node_modules/db-mysql/wscript:22: error: could not configure a cxx compiler!
npm ERR! error installing db-mysql@0.6.6 Error: db-mysql@0.6.6 install: `node-waf configure build`
npm ERR! error installing db-mysql@0.6.6 `sh "-c" "node-waf configure build"` failed with 1
npm ERR! error installing db-mysql@0.6.6     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing db-mysql@0.6.6     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing db-mysql@0.6.6     at ChildProcess.onexit (child_process.js:192:12)

> db-mysql@0.6.6 preuninstall /Users/adamfisher/node_modules/db-mysql
> rm -rf build/*

npm ERR! db-mysql@0.6.6 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the db-mysql@0.6.6 install script.
npm ERR! This is most likely a problem with the db-mysql package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls db-mysql
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Darwin 10.7.0
npm ERR! command "node" "/usr/bin/npm" "install" "db-mysql"
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/adamfisher/npm-debug.log
npm not ok
```

**Comment by mariano** [comment]
@adamfisher: This part of the output:

```
/Users/adamfisher/node_modules/db-mysql/wscript:22: error: could not configure a cxx compiler!
```

Is telling you that there's no C++ compiler in your system, and you obviously need that to get going.

I also see that you closed the issue. Did you close the issue because you solved the problem? If so, could you document how you solved it to avoid other users from experiencing the same? Thanks

**Comment by adamhalasz** [comment]
mariano , thanks very much for the reply, yes I solved it. 

I noticed that the problem was with `Checking for program g++ or c++          : not found` I read about it and turned out that on my Mac I need to install Xcode because the compilers are shipped in it. I installed it from my Leopard DVD and then worked.

But then I've got a new problem with MySQL, db-mysql module is not working with the latest MySQL 5.5.13, but works with 5.1.57. I will post this issue as a separate thread a bit later, and reproduce the errors too.

**Comment by mariano** [comment]
Ok, if you are trying to make it work with a newer version of MySQL, you obviously have to link it against those newer libraries

**Comment by adamhalasz** [comment]
hey that was fast :)) what do you mean under `those newer libraries`?

**Comment by mariano** [comment]
Actually i may be wrong, but if MySQL 5.5 introduces changes that require libmysql to be updated, then db-mysql would have to be compiled with the newer version of libmysql. But I'm not sure if MySQL 5.5 is backwards compatible or not. In any case it'd be useful to have that ticket reported with as much information as possible

**Comment by mariano** [comment]
Actually MySQL 5.5 has no issues whatsoever. I just didn't know which version I was testing it with on my ArchLinux installation.

So the following connections are tested:

Using libmysql 5.5 for connecting to MySQL 5.5.13: WORKS
Using libmysql 5.1 for connecting to MySQL 5.1.54: WORKS
Using libmysql 5.1 for connecting to MySQL 5.5.13: WORKS
