### ISSUE TITLE
big integers broken

### ISSUE THREAD

**Issue by alexbirkett** [mariano/node-db-mysql#24]
Consider the following code snippet:

```
var long = 70686626206955;
console.log("long type " + typeof long + " long value " + long);

var query = db.query().insert("table", ["long"],
        [{value: long, escape: true}]);

console.log("sql ",query.sql());
```

it produces:

long type number long value 70686626206955
sql  INSERT INTO `table`(`long`) VALUES (7.06866e+13)

7.06866e+13 is not equivalent to 70686626206955 (precision is lost)

**Comment by mariano** [comment]
Fixed in 288a9f2fb856b0add9ef35357adad24bec566214
