### ISSUE TITLE
NPM installation error

### ISSUE THREAD

**Issue by vossoug** [mariano/node-db-mysql#29]
I'm running RED HAT Enterprise 5.7 with node 0.4.10 and npm 1.0.25 and I'm running into an error message when trying to install db-mysql. After running "sudo npm install db-mysql," this is my output.

> node-waf configure build
> Checking for program g++ or c++          : /usr/bin/g++
> Checking for program cpp                 : /usr/bin/cpp
> Checking for program ar                  : /usr/bin/ar
> Checking for program ranlib              : /usr/bin/ranlib
> Checking for g++                         : ok
> Checking for node path                   : not found
> Checking for node prefix                 : ok /usr/local
> Checking for program mysql_config        : /usr/bin/mysql_config
> Checking for library mysqlclient_r       : Missing libmysqlclient_r
> 'configure' finished successfully (0.135s)
> Waf: Entering directory `/apps/home/hotseat/node_modules/db-mysql/build'
> [ 1/11] cxx: lib/node-db/binding.cc -> build/default/lib/node-db/binding_1.o
> [ 2/11] cxx: lib/node-db/connection.cc -> build/default/lib/node-db/connection_1.o
> [ 3/11] cxx: lib/node-db/exception.cc -> build/default/lib/node-db/exception_1.o
> [ 4/11] cxx: lib/node-db/query.cc -> build/default/lib/node-db/query_1.o
> [ 5/11] cxx: lib/node-db/result.cc -> build/default/lib/node-db/result_1.o
> [ 6/11] cxx: src/connection.cc -> build/default/src/connection_1.o
> In file included from ../src/connection.cc:2:
> ../src/./connection.h:5:19: error: mysql.h: No such file or directory
> ../src/././result.h:16: error: expected â,â or â...â before â&â token
> ../src/././result.h:16: error: ISO C++ forbids declaration of âMYSQL_FIELDâ with no type
> ../src/././result.h:28: error: expected`)' before â*â token
> (and it goes on for another 40 lines or so)

running a "which mysql_config", my file is: /usr/bin/mysql_config. The /usr/bin  mysqlclient_r directory is also in my path and my path is no different than my regular account.

I ran a search, but was unable to locate the  mysqlclient_r  file. I am however able to log on to the mysql server (v. 5.0.77) and run queries manually.

Does anyone know a way around this problem?

**Comment by mariano** [comment]
Please test again with the new release
