### ISSUE TITLE
Connect to socket

### ISSUE THREAD

**Issue by snowtorious** [mariano/node-db-mysql#3]
Is it possible to connect directly to a socket instead of connecting to a host/port? For example, on OSX, mysql uses a socket file, /tmp/mysql.sock, by default.

**Comment by mariano** [comment]
You can now, as of version 0.4.6 (just released). To connect through a socket you can do:

```
new mysql.Database({
    socket: '/tmp/mysql.sock',
    user: 'user',
    password: 'password',
    database: 'my_db'
}).on('error', function(err) { 
    console.log('CONNECT ERROR: ' + err);
}).on('ready', function(s) {
    console.log('CONNECTED to ' + s.hostname + ' (' + s.version + ')');
}).connect();
```

You'll need to reinstall/update db-mysql.
