### ISSUE TITLE
Installation on Ubuntu 11.04

### ISSUE THREAD

**Issue by scull7** [mariano/node-db-mysql#32]
I'm having an issue getting the db-mysql library installed through NPM.  

uname -r output: Linux nathan-rcsg-dev 2.6.38-11-server #50-Ubuntu SMP Mon Sep 12 21:34:27 UTC 2011 x86_64 x86_64 x86_64 GNU/Linux

Here's the output of  "npm install db-mysql"

npm install -g db-mysql

> db-mysql@0.6.7 install /usr/local/lib/node_modules/db-mysql
> node-waf configure build

Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
Checking for program mysql_config        : /usr/bin/mysql_config 
Checking for library mysqlclient_r       : no such environment: default
Traceback (most recent call last):
  File "/usr/local/bin/node-waf", line 16, in <module>
    Scripting.prepare(t, os.getcwd(), VERSION, wafdir)
  File "/usr/local/bin/../lib/node/wafadmin/Scripting.py", line 145, in prepare
    prepare_impl(t, cwd, ver, wafdir)
  File "/usr/local/bin/../lib/node/wafadmin/Scripting.py", line 135, in prepare_impl
    main()
  File "/usr/local/bin/../lib/node/wafadmin/Scripting.py", line 188, in main
    fun(ctx)
  File "/usr/local/bin/../lib/node/wafadmin/Scripting.py", line 241, in configure
    conf.sub_config([''])
  File "/usr/local/bin/../lib/node/wafadmin/Configure.py", line 221, in sub_config
    self.recurse(k, name='configure')
  File "/usr/local/bin/../lib/node/wafadmin/Utils.py", line 634, in recurse
    f(self)
  File "/usr/local/lib/node_modules/db-mysql/wscript", line 38, in configure
    conf.check_cxx(lib="mysqlclient_r", errmsg="Missing libmysqlclient_r")
  File "/usr/local/bin/../lib/node/wafadmin/Tools/config_c.py", line 567, in check_cxx
    return self.check(_k, *_kw)
  File "/usr/local/bin/../lib/node/wafadmin/Tools/config_c.py", line 444, in check
    ret = self.run_c_code(_k, *_kw)
  File "/usr/local/bin/../lib/node/wafadmin/Tools/config_c.py", line 521, in run_c_code
    o = bld(features=kw['features'], source=test_f_name, target='testprog')
  File "/usr/local/bin/../lib/node/wafadmin/Build.py", line 343, in **call**
    return TaskGen.task_gen(_k, *_kw)
  File "/usr/local/bin/../lib/node/wafadmin/TaskGen.py", line 118, in **init**
    self.env = self.bld.env.copy()
AttributeError: 'NoneType' object has no attribute 'copy'

Any ideas?

**Comment by ghost** [comment]
I have this same issue, but am using 2.6.38-11-generic instead of server.

**Comment by mariano** [comment]
Please test again with the new release

**Comment by scull7** [comment]
npm install db-mysql attempts to install 0.7.0 but it still results in the same issue.

nsculli@nathan-rcsg-dev:~/psync$ npm install db-mysql

> db-mysql@0.7.0 install /home/nsculli/psync/node_modules/db-mysql
> node-waf configure build

Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
Checking for program mysql_config        : /usr/bin/mysql_config 
Checking for library mysqlclient_r       : no such environment: default
Traceback (most recent call last):
  File "/usr/local/bin/node-waf", line 16, in <module>
    Scripting.prepare(t, os.getcwd(), VERSION, wafdir)
  File "/usr/local/bin/../lib/node/wafadmin/Scripting.py", line 145, in prepare
    prepare_impl(t, cwd, ver, wafdir)
  File "/usr/local/bin/../lib/node/wafadmin/Scripting.py", line 135, in prepare_impl
    main()
  File "/usr/local/bin/../lib/node/wafadmin/Scripting.py", line 188, in main
    fun(ctx)
  File "/usr/local/bin/../lib/node/wafadmin/Scripting.py", line 241, in configure
    conf.sub_config([''])
  File "/usr/local/bin/../lib/node/wafadmin/Configure.py", line 221, in sub_config
    self.recurse(k, name='configure')
  File "/usr/local/bin/../lib/node/wafadmin/Utils.py", line 634, in recurse
    f(self)
  File "/home/nsculli/psync/node_modules/db-mysql/wscript", line 38, in configure
    conf.check_cxx(lib="mysqlclient_r", errmsg="Missing libmysqlclient_r")
  File "/usr/local/bin/../lib/node/wafadmin/Tools/config_c.py", line 567, in check_cxx
    return self.check(_k, *_kw)
  File "/usr/local/bin/../lib/node/wafadmin/Tools/config_c.py", line 444, in check
    ret = self.run_c_code(_k, *_kw)
  File "/usr/local/bin/../lib/node/wafadmin/Tools/config_c.py", line 521, in run_c_code
    o = bld(features=kw['features'], source=test_f_name, target='testprog')
  File "/usr/local/bin/../lib/node/wafadmin/Build.py", line 343, in **call**
    return TaskGen.task_gen(_k, *_kw)
  File "/usr/local/bin/../lib/node/wafadmin/TaskGen.py", line 118, in **init**
    self.env = self.bld.env.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
npm ERR! error installing db-mysql@0.7.0 Error: db-mysql@0.7.0 install: `node-waf configure build`
npm ERR! error installing db-mysql@0.7.0 `sh "-c" "node-waf configure build"` failed with 1
npm ERR! error installing db-mysql@0.7.0     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing db-mysql@0.7.0     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing db-mysql@0.7.0     at ChildProcess.onexit (child_process.js:192:12)

> db-mysql@0.7.0 preuninstall /home/nsculli/psync/node_modules/db-mysql
> rm -rf build/*

npm ERR! db-mysql@0.7.0 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the db-mysql@0.7.0 install script.
npm ERR! This is most likely a problem with the db-mysql package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls db-mysql
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 2.6.38-11-server
npm ERR! command "node" "/usr/local/bin/npm" "install" "db-mysql"
npm ERR! cwd /home/nsculli/psync
npm ERR! node -v v0.4.12
npm ERR! npm -v 1.0.90
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/nsculli/psync/npm-debug.log
npm not ok

**Comment by markwillis82** [comment]
Hi - I receive a different issue on ubuntu 11.10 and mysql 5.1:

> db-mysql@0.7.5 install /tmp/b-mysql/node_modules/db-mysql
> node-waf configure build

Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /home/mark/node 
Checking for program mysql_config        : /usr/bin/mysql_config 
Checking for library mysqlclient_r       : yes 
'configure' finished successfully (0.535s)
Waf: Entering directory `/tmp/b-mysql/node_modules/db-mysql/build'
[ 1/12] cxx: lib/node-db/binding.cc -> build/default/lib/node-db/binding_1.o
[ 2/12] cxx: lib/node-db/connection.cc -> build/default/lib/node-db/connection_1.o
[ 3/12] cxx: lib/node-db/events.cc -> build/default/lib/node-db/events_1.o
[ 4/12] cxx: lib/node-db/exception.cc -> build/default/lib/node-db/exception_1.o
../lib/node-db/events.cc: In static member function ‘static void node_db::EventEmitter::Init()’:
../lib/node-db/events.cc:13:14: error: ‘Persistent’ was not declared in this scope
../lib/node-db/events.cc:13:14: note: suggested alternative:
/home/mark/node/include/node/v8.h:100:26: note:   ‘v8::Persistent’
../lib/node-db/events.cc:13:14: error: ‘String’ was not declared in this scope
../lib/node-db/events.cc:13:14: note: suggested alternative:
/home/mark/node/include/node/v8.h:973:7: note:   ‘v8::String’
../lib/node-db/events.cc:13:14: error: ‘::New’ has not been declared
../lib/node-db/events.cc:13:14: error: ‘String’ is not a class or namespace
Waf: Leaving directory`/tmp/b-mysql/node_modules/db-mysql/build'
Build failed:  -> task failed (err #1): 
    {task: cxx events.cc -> events_1.o}
npm info db-mysql@0.7.5 Failed to exec install script
npm ERR! error installing db-mysql@0.7.5 Error: db-mysql@0.7.5 install: `node-waf configure build`
npm ERR! error installing db-mysql@0.7.5 `sh "-c" "node-waf configure build"` failed with 1
npm ERR! error installing db-mysql@0.7.5     at ChildProcess.<anonymous> (/home/mark/node/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing db-mysql@0.7.5     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing db-mysql@0.7.5     at ChildProcess.onexit (child_process.js:192:12)
npm info unbuild /tmp/b-mysql/node_modules/db-mysql
npm verb from cache /tmp/b-mysql/node_modules/db-mysql/package.json
npm info preuninstall db-mysql@0.7.5
npm verb unsafe-perm in lifecycle true

> db-mysql@0.7.5 preuninstall /tmp/b-mysql/node_modules/db-mysql
> rm -rf build/*

npm info uninstall db-mysql@0.7.5
npm verb unbuild db-mysql@0.7.5 [ false,
npm verb unbuild db-mysql@0.7.5   '/home/mark/node/lib/node_modules',
npm verb unbuild db-mysql@0.7.5   '/tmp/b-mysql/node_modules' ]
npm info postuninstall db-mysql@0.7.5
npm verb installOne cb db-mysql@0.7.5
npm ERR! db-mysql@0.7.5 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the db-mysql@0.7.5 install script.
npm ERR! This is most likely a problem with the db-mysql package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls db-mysql
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 3.0.0-12-generic
npm ERR! command "node" "/home/mark/node/bin/npm" "install" "db-mysql" "-verbose"
npm ERR! cwd /tmp/b-mysql
npm ERR! node -v v0.4.9
npm ERR! npm -v 1.0.27
npm verb exit [ 1, true ]
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /tmp/b-mysql/npm-debug.log
npm not ok

Looks like a test is failing

**Comment by mariano** [comment]
@markwillis82 what node version is that with? Because that scope issue on NODE_PSYMBOL, which is part of node header files, has been solved on recent node releases.

**Comment by markwillis82** [comment]
node -v
v0.4.9

will upgrade this evening to 0.6 and try again

**Comment by mariano** [comment]
Actually I'm going to fix it in the code so it can compile on node 0.4.x. Give me a sec

**Comment by mariano** [comment]
@markwillis82 try now. Release notes: http://nodejsdb.org/2011/11/node-db-drivers-updated-9/

**Comment by markwillis82** [comment]
Compiled successfully.

Excellent support.

'configure' finished successfully (1.690s)
Waf: Entering directory `/tmp/db-mysql/node_modules/db-mysql/build'
[ 1/12] cxx: lib/node-db/binding.cc -> build/default/lib/node-db/binding_1.o
[ 2/12] cxx: lib/node-db/connection.cc -> build/default/lib/node-db/connection_1.o
[ 3/12] cxx: lib/node-db/events.cc -> build/default/lib/node-db/events_1.o
[ 4/12] cxx: lib/node-db/exception.cc -> build/default/lib/node-db/exception_1.o
[ 5/12] cxx: lib/node-db/query.cc -> build/default/lib/node-db/query_1.o
[ 6/12] cxx: lib/node-db/result.cc -> build/default/lib/node-db/result_1.o
[ 7/12] cxx: src/connection.cc -> build/default/src/connection_1.o
[ 8/12] cxx: src/mysql.cc -> build/default/src/mysql_1.o
[ 9/12] cxx: src/query.cc -> build/default/src/query_1.o
[10/12] cxx: src/result.cc -> build/default/src/result_1.o
[11/12] cxx: src/mysql_bindings.cc -> build/default/src/mysql_bindings_1.o
[12/12] cxx_link: build/default/lib/node-db/binding_1.o build/default/lib/node-db/connection_1.o build/default/lib/node-db/events_1.o build/default/lib/node-db/exception_1.o build/default/lib/node-db/query_1.o build/default/lib/node-db/result_1.o build/default/src/connection_1.o build/default/src/mysql_1.o build/default/src/query_1.o build/default/src/result_1.o build/default/src/mysql_bindings_1.o -> build/default/mysql_bindings.node
Waf: Leaving directory`/tmp/db-mysql/node_modules/db-mysql/build'
'build' finished successfully (4.537s)
npm info postinstall db-mysql@0.7.6
npm verb installOne cb db-mysql@0.7.6
db-mysql@0.7.6 ./node_modules/db-mysql 
npm verb exit [ 0, true ]
npm info ok
