### ISSUE TITLE
Reusing connections

### ISSUE THREAD

**Issue by NHQ** [mariano/node-db-mysql#34]
In the examples, all actions are chained to the original Database class, through .connect(). Eg. I was unable to do this:

```
var mysql = require('db-mysql');
new mysql.Database({
    hostname: 'hyfnrsx.com',
    user: 'remote',
    password: '2bq44acLtPTx2D46',
    database: 'online-presence-scrubber'
}).connect(function(error) {})

// something else happening

mysql.query().select('..') ...

// or 

mysql.Database.query()...
```

Is there a way to reuse the options and connection for later querying?

**Comment by mariano** [comment]
First of all you are not doing it right, since the queries are run asynchronously.

That is if you do:

``` javascript
new mysql.Database({ .... }).connect(function() {
     // On connect
});
console.log("HERE");
```

The HERE will be outputted before the DB is even connected.

Even if you still wanted to do that, a very basic assignment solves your requirement:

``` javascript
var db = new mysql.Database({ .... });

db.connect(function() {
     // On connect
});
console.log("HERE");
db.query()...
```

But remember, you need to think async-ly.

**Comment by NHQ** [comment]
Foolishly I missed that the connection in the example was declared as a constructor, not as assignment. DUMB!

Thanks!
