### ISSUE TITLE
Support for "ON DUPLICATE KEY UPDATE"

### ISSUE THREAD

**Issue by bbigras** [mariano/node-db-mysql#36]
Any plans to supports "ON DUPLICATE KEY UPDATE" on INSERT queries?

**Comment by mariano** [comment]
First of all, remember that you can still use manual queries, which have no restrictions on the SQL statements you can send.

As to adding a method API for it, I'll do it together with #23

**Comment by jkeys089** [comment]
Is this still in the queue?
