### ISSUE TITLE
SQL Syntax errors bubbling up as unspecified error: "Unknown Error".

### ISSUE THREAD

**Issue by deyceg** [mariano/node-db-mysql#39]
I've got a query with an on error handler attached. I've noticed that I am unable to log the query (with bind parameters) I am about to execute to the console prior to .execute. Also, when there is a syntax error (or any error emitted during query execution), the error caught is an unspecified error: (unknown error).

This is against 0.7.4

Example:

```
self.query().
    on('error', function(error) {
        //handle error
    }).
    execute('some malformed sql', function(error, result) {
        if (error) {
            //handle error
        }
        else {
            //alls good!
        }
    });
```

**Comment by mariano** [comment]
Weird, I can't replicate this. I'm doing:

``` javascript
var mysql = require("./db-mysql");

new mysql.Database({
    hostname: 'localhost',
    user: 'root',
    password: 'password',
    database: 'node'
}).
connect(function(error, server) {
    if (error) {
        return console.log('ERROR while connecting: ' + error);
    }

    this.query().
    on('error', function(error) {
        console.log('QUERY ERROR HANDLER: ' + error);
    }).
    execute('some malformed sql', function(error, result) {
        if (error) {
            return console.log('ERROR while executing query: ' + error);
        } else {
            console.log('RESULTS: ', result);
        }
    });
});
```

And I get the following output:

``` bash
$ node test.js
QUERY ERROR HANDLER: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'some malformed sql' at line 1
ERROR while executing query: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'some malformed sql' at line 1
```

Going to improve how the error string is passed on to JS lang, though. But in the meantime could you tell me OS?

**Comment by deyceg** [comment]
OS is Debian Linux.

Would it make any difference that I'm using async=false on the query?

**Comment by deyceg** [comment]
I've just checked your code and I get the error message! If I do:

```
this.query({'async':false}).
                on('error', function(error) {
                    console.log('QUERY ERROR HANDLER: ' + error);
                }).
                execute('some malformed sql', function(error, result) {
                    if (error) {
                        return console.log('ERROR while executing query: ' + error);
                    } else {
                        console.log('RESULTS: ', result);
                    }
                });
```

I get an error every time a start node, and on every invocation of the query.

**Comment by mariano** [comment]
Yup, that tells me that is probably related to a pointer issue.

Eventhough I can't replicate, I'm working on a possible fix. In order for you to test it, you'd have to go back to async queries, and compile node-db from latest source (node-waf configure build). Are you comfortable doing that?

**Comment by deyceg** [comment]
Semi-comfortable - I can definitely have a go on the weekend (going to be busy rest of today/tomorrow). The main impact of this for me is not being able to easily identify syntax errors for synchronous queries - As a workaround I can run them asynchronously first. 

I should probably raise this as a separate issue, but would it be possible to explain what is happening differently when you set the async flag to false?

Also, am I correct to assume nested joins are not supported yet? I am struggling to even get a single (left) join working at the moment and resorting to hardcoding the sql and using .execute().

**Comment by mariano** [comment]
Ok, first of all the different between async and sync queries is no different than thinking about sync and async methods in regular nodeJS modules. Sync means it happens on the same thread (async = false), and async queries (async = true, which is the default) means the actual query happens on a different thread, allowing your main thread to continue working without waiting for query results. It is absolutely recommended in Node to do everything async (default in nodedb)

I see no reason why you can't use multiple joins. I'm adding a new test that does the following:

``` javascript
query = client.query().join(
{
        "table": "profiles",
        "alias": "p",
        "conditions": "p.id = u.profile_id AND approved = ? AND created >= ?"
    },
    [ 1, new Date(2011, 2, 12, 19, 49, 0) ]
).join({·
    "table": "contacts",
    "alias": "c",
    "conditions": "c.id = p.contact_id"
}).execute(...);
```

That produces the query:

``` sql
INNER JOIN `profiles` AS `p` ON (p.id = u.profile_id AND approved = 1 AND created >= '2011-03-12 19:49:00') INNER JOIN `contacts` AS `c` ON (c.id = p.contact_id)
```

**Comment by deyceg** [comment]
Regarding sync - I need to do multiple inserts as part transaction so I may need to rollback at any point during the transaction and without a transaction management framework (in the middle-tier sense) I'm having to resort to database transaction management:

START TRANSACTION
//Execute queries
COMMIT;

This is requiring me to set the async flag to false or I won't know when my transaction has finished. I'm quite new to nodejs and haven't come across any examples for this use case.

I'll re-attempt the join this evening.

**Comment by mariano** [comment]
I think I solved the error issue, so you won't need to compile it yourself.

Will package in 2'.

**Comment by mariano** [comment]
Fix released http://nodejsdb.org/2011/11/node-db-drivers-updated-8/

Try and let me know

**Comment by deyceg** [comment]
Thanks,

I'll test in the morning!

**Comment by deyceg** [comment]
Good evening Mariano,

Just wanted to let you know thats all sorted now and I managed to get my join working.

**Comment by mariano** [comment]
Awesome, glad it worked!
