### ISSUE TITLE
Nodejs and db-mysql

### ISSUE THREAD

**Issue by tylervortex** [mariano/node-db-mysql#43]
I wanted to take this code to query the data stored in the database but can not find documentation for this:

http://nodejsdb.org/db-mysql/

**Comment by mariano** [comment]
What do you mean? The nodejsdb.org site is filled with documentation!

**Comment by tylervortex** [comment]
Well, I tried to print the data in console.log () and found nothing in the documentation.
I'm new to the node, as expected I guess?
Sorry if I can not for the little you have in your doc.
Att
