### ISSUE TITLE
update escape Values

### ISSUE THREAD

**Issue by Fantus** [mariano/node-db-mysql#49]
Its not possible to update a timestamp col with "NOW()" or i missed something.

connection.query()
                .update('xxx')
                .set({ 'last_used': "NOW()"}, false)
                .where('id = ' + id)

with false set only the col names will no longer be escaped

regards
Justus

**Comment by tomasikp** [comment]
connection.query()
.update('xxx')
.set({ 'last_used':{value: 'NOW', escape: false}}, false)
.where('id = ' + id)

**Comment by mariano** [comment]
Just as @tomasikp pointed out, use the escape:false attribute
