### ISSUE TITLE
placerholders are not replaced

### ISSUE THREAD

**Issue by Fantus** [mariano/node-db-mysql#50]
Tried it serveral times. copied the example from the website anyway its not working :(

console.log(connection.query()
                .update('map_value')
                .set({ 'last_used': "NOW()"})
                .where('id = ?', [id])
                .sql();
returns this
UPDATE `map_value` SET `last_used`='NOW()' WHERE id = ?

regards 
Fantus

**Comment by kmulvey** [comment]
+1  .... would like this

**Comment by mariano** [comment]
Duplicate of #49 and already answered there
