### ISSUE TITLE
Trouble with columns object

### ISSUE THREAD

**Issue by boozedog** [mariano/node-db-mysql#57]
`JSON.stringify(columns)` gives this:

```
[{"name":"id","type":2},
{"name":"url","type":0},
{"name":"create_ts","type":6},
{"name":"update_ts","type":6}]
```

but when I run the following code:

```
for (col in columns) {
    console.log(col.name + ' ' + col.type);
}
```

I'm getting `undefined` for both `name` and `type` .

Any ideas? Apologies in advance if I'm missing something obvious ...

**Comment by mengy007** [comment]
Try this columns[col].name and columns[col].type
I believe col is the index and not the actual object. I could be wrong.

**Comment by boozedog** [comment]
You're right ... I need to read my Javascript manual more carefully, LOL

Thanks for your help!

**Comment by mengy007** [comment]
Glad I could help. =]
