### ISSUE TITLE
not able to install db-mysql on ubuntu 11.04

### ISSUE THREAD

**Issue by apdarshan** [mariano/node-db-mysql#58]
npm install db-mysql;

npm http GET https://registry.npmjs.org/db-mysql
npm http 304 https://registry.npmjs.org/db-mysql

> db-mysql@0.7.6 install /var/www/fm/public/node_modules/db-mysql
> node-waf configure build

Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
Checking for program mysql_config        : /usr/bin/mysql_config 
Checking for library mysqlclient_r       : yes 
'configure' finished successfully (1.378s)
Waf: Entering directory `/var/www/fm/public/node_modules/db-mysql/build'
[ 1/12] cxx: lib/node-db/binding.cc -> build/Release/lib/node-db/binding_1.o
[ 2/12] cxx: lib/node-db/connection.cc -> build/Release/lib/node-db/connection_1.o
[ 3/12] cxx: lib/node-db/events.cc -> build/Release/lib/node-db/events_1.o
[ 4/12] cxx: lib/node-db/exception.cc -> build/Release/lib/node-db/exception_1.o
[ 5/12] cxx: lib/node-db/query.cc -> build/Release/lib/node-db/query_1.o
../lib/node-db/binding.cc: In static member function ‘static v8::Handle<v8::Value> node_db::Binding::Connect(const v8::Arguments&)’:
../lib/node-db/binding.cc:86:76: error: too few arguments to function ‘eio_req* eio_custom(void (*)(eio_req*), int, eio_cb, void*, eio_channel*)’
/usr/local/include/node/uv-private/eio.h:361:10: note: declared here
../lib/node-db/query.cc: In static member function ‘static v8::Handle<v8::Value> node_db::Query::Execute(const v8::Arguments&)’:
../lib/node-db/query.cc:646:76: error: too few arguments to function ‘eio_req* eio_custom(void (*)(eio_req*), int, eio_cb, void*, eio_channel*)’
/usr/local/include/node/uv-private/eio.h:361:10: note: declared here
Waf: Leaving directory`/var/www/fm/public/node_modules/db-mysql/build'
Build failed:
 -> task failed (err #1): 
    {task: cxx binding.cc -> binding_1.o}
 -> task failed (err #1): 
    {task: cxx query.cc -> query_1.o}
npm ERR! error installing db-mysql@0.7.6

> db-mysql@0.7.6 preuninstall /var/www/fm/public/node_modules/db-mysql
> rm -rf build/*

npm ERR! db-mysql@0.7.6 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the db-mysql@0.7.6 install script.
npm ERR! This is most likely a problem with the db-mysql package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls db-mysql
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 3.0.0-15-generic
npm ERR! command "node" "/usr/local/bin/npm" "install" "db-mysql"
npm ERR! cwd /var/www/fm/public
npm ERR! node -v v0.7.3-pre
npm ERR! npm -v 1.1.0-2
npm ERR! code ELIFECYCLE
npm ERR! message db-mysql@0.7.6 install: `node-waf configure build`
npm ERR! message `sh "-c" "node-waf configure build"` failed with 1
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/fm/public/npm-debug.log

npm not ok

**Comment by vanng822** [comment]
I have the same issue (for db-mysql@0.7.6) with

Ubuntu 11.10
node -v v0.7.6-pre
npm -v 1.1.4

**Comment by vanng822** [comment]
eio_channel was added https://github.com/joyent/node/commit/dd0188ec088fc87ee689e4efa193e241199de615

eio_req _eio_custom    (void (_execute)(eio_req *), int pri, eio_cb cb, void *data, eio_channel *channel);

**Comment by vanng822** [comment]
Ignore me :-)

It works fine with node v0.6.12

**Comment by apdarshan** [comment]
Thanks , Works fine with node version 0.6.8
