### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _mysql_init

### ISSUE THREAD

**Issue by mackjoner** [mariano/node-db-mysql#68]
localhost:devsample yangzhaojie$ node app15.js 
dyld: lazy symbol binding failed: Symbol not found: _mysql_init
  Referenced from: /Users/yangzhaojie/tech/nodejs/node_modules/db-mysql/build/Release/mysql_bindings.node
  Expected in: flat namespace

dyld: Symbol not found: _mysql_init
  Referenced from: /Users/yangzhaojie/tech/nodejs/node_modules/db-mysql/build/Release/mysql_bindings.node
  Expected in: flat namespace

I set's /etc/profile export MYSQL_CONFIG=/usr/local/mysql/bin/mysql_config
run this example code, get something of the exception.
OS:Mac OS X Lion 10.7.3
NODEJS:0.6.11
MYSQL:5.1

**Comment by chenmingqiang** [comment]
maybe you should install mysql x86_64.

**Comment by mackjoner** [comment]
@chenmingqiang yes, it's worked on the version.

**Comment by mackjoner** [comment]
mysql x86_64

**Comment by jvanalst** [comment]
I just bumped into this. Is there any reason why we aren't supporting the 32-bit version? You'd think that would be a fairly common use case.

Personally, I can't use the library now because I can't change out mysql versions on a production machine at the drop of a hat.
