### ISSUE TITLE
TypeError: Object [object Object] has no method 'execute'

### ISSUE THREAD

**Issue by joakim** [mariano/node-db-mysql#8]
I can't get the execute() to work, but I might be doing something wrong?

My code:

```
new mysql.Database({
    'hostname': 'localhost',
    'user':     'user',
    'password': 'pass',
    'database': 'db'
}).connect(function(error) {
    if (error) {
        return console.log('MySQL connection error: ' + error);
    }
    this.execute(…);
});
```

This is the error I get:

```
this.execute(…) {
     ^
TypeError: Object [object Object] has no method 'execute'
at [object Object].<anonymous> (/srv/www/server.js:35:9)
```

**Comment by mariano** [comment]
As per the [Database documentation](http://nodejsdb.org/docs/), you first need to get an instance of the [Query](http://nodejsdb.org/docs/#query) class before running execute:

```
new mysql.Database({
    'hostname': 'localhost',
    'user':     'user',
    'password': 'pass',
    'database': 'db'
}).connect(function(error) {
    if (error) {
        return console.log('MySQL connection error: ' + error);
    }
    this.query().execute(…);
});
```

This is also shown in the [quick guide to db-mysql](http://nodejsdb.org/db-mysql/)

**Comment by joakim** [comment]
Thank you for the (blazingly) quick answer! I thought execute() worked without query(), but I should've RTFM more carefully.

**Comment by mariano** [comment]
haha no worries. I'm working on implementing db-oracle so i was in github already :)
