### ISSUE TITLE
Failure to Install on ArchLinux

### ISSUE THREAD

**Issue by geekinthesticks** [mariano/node-db-mysql#98]
Sanity check:
scamper2 computer/nodejs ‹master*› » which mysql_config
/usr/bin/mysql_config

Partial log:

133 verbose true,/home/ian/Documents/emacs/org/org_files/computer/nodejs/node_modules,/home/ian/Documents/emacs/org/org_files/computer/nodejs/node_modules unbuild db-mysql@0.7.6
134 info postuninstall db-mysql@0.7.6
135 error db-mysql@0.7.6 install: `node-waf configure build`
135 error `sh "-c" "node-waf configure build"` failed with 127
136 error Failed at the db-mysql@0.7.6 install script.
136 error This is most likely a problem with the db-mysql package,
136 error not with npm itself.
136 error Tell the author that this fails on your system:
136 error     node-waf configure build
136 error You can get their info via:
136 error     npm owner ls db-mysql
136 error There is likely additional logging output above.
137 error System Linux 3.8.3-2-ARCH
138 error command "/usr/bin/node" "/usr/bin/npm" "install" "db-mysql"
139 error cwd /home/ian/Documents/emacs/org/org_files/computer/nodejs
140 error node -v v0.10.0
141 error npm -v 1.2.14
142 error code ELIFECYCLE
143 verbose exit [ 1, true ]

**Comment by raadad** [comment]
As of node.js v0.8 node-waf was removed and replaced with node-gyp, I think the maintainers finishing up all the work needed for this to install on the current version of node. If you pull down the latest source and master branch you can get this working. I did it the following way 
1. Cloning current repository with the --recursive option
2. checked out the master of  the submodule "node-db" - located in lib/node-db  ( just navigate here and execute  "git checkout master"
3. Installed node-gyp from via npm
4. Edited the package.json file and changed node-waf to node-gyp on line 21
5. execute npm install from the base directory

And vwallah it all compiled and installed fine and now I can run my systems on the newest version of node

**Comment by geekinthesticks** [comment]
Thanks, I have managed to do steps 1-4. However, I an not sure what you mean by "Wxecuted npm install from the base directory". Do I just "npm install" with no arguments.

**Comment by raadad** [comment]
After you have done a npm install, it will prepare the library, then if there are no errors all you have to do is place the whole directory into your projects node_modules folder and then you can require eg: require('node-db-mysql');

**Comment by geekinthesticks** [comment]
Thank you that worked nicely, after I had worked out that there was an error in the quick start guide, which I'll post as a separate issue..

**Comment by ivandokov** [comment]
> db-mysql@0.7.6 install /Users/ivan/Sites/git_svn/node-db-mysql
> node-gyp rebuild
> 
> CXX(target) Release/obj.target/mysql_bindings/lib/node-db/exception.o
> CXX(target) Release/obj.target/mysql_bindings/lib/node-db/binding.o 
> ../lib/node-db/binding.cc:111:26: error: use of undeclared identifier 'exception' request->error = exception.what();
> ../lib/node-db/binding.cc:208:25: error: use of undeclared identifier 'exception' THROW_EXCEPTION(exception.what())
> ../lib/node-db/./node_defs.h:26:68: note: expanded from macro 'THROW_EXCEPTION' return v8::ThrowException(v8::Exception::Error(v8::String::New(message)));
> ../lib/node-db/binding.cc:229:25: error: use of undeclared identifier 'exception' THROW_EXCEPTION(exception.what())
> ../lib/node-db/./node_defs.h:26:68: note: expanded from macro 'THROW_EXCEPTION' return v8::ThrowException(v8::Exception::Error(v8::String::New(message)));
> 
> 3 errors generated.
> make: **\* [Release/obj.target/mysql_bindings/lib/node-db/binding.o] Error 1
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:256:23)
> gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:754:12)
> gyp ERR! System Darwin 12.3.0
> gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /Users/ivan/Sites/git_svn/node-db-mysql
> gyp ERR! node -v v0.10.0
> gyp ERR! node-gyp -v v0.8.5
> gyp ERR! not ok 
> npm ERR! db-mysql@0.7.6 install: `node-gyp rebuild`
> npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1

This is the error I receive when I try npm install (5th step).
OS X Mountain Lion

**Comment by crooner** [comment]
"As of node.js v0.8 node-waf was removed and replaced with node-gyp, I think the maintainers finishing up all the work needed for this to install on the current version of node. If you pull down the latest source and master branch you can get this working. I did it the following way"

Why don't they just fix it properly instead of having to muck about behind the scenes just to get it working?

**Comment by lexblagus** [comment]
Same problem on Mac OS 10.8.4/Node 0.10.15, waiting for a official fix.

**Comment by darumaGit** [comment]
Hello Raadad, I have this prob also. Could you please be more verbose about what to do to solve this task. I mean wouldn't you show the exact commands to be entered? I am completely new to major things you mention in the steps above. Very appreciate

**Comment by raadad** [comment]
I don't get the same issue as you guys, however just running the command: "npm install db-mysql" does not work for me.

The following did:

cd node_modules
git clone  https://github.com/mariano/node-db-mysql.git
mv node-db-mysql db-mysql
cd db-mysql
npm install

I'm running:

mysql  Ver 14.14 Distrib 5.6.19-67.0, for Linux (x86_64) using  EditLine wrapper
mysql_config 10.0.12
node v0.10.28

Hope that helps.

**Comment by pornthipw** [comment]
Thank you very much @raadad
